### ISSUE TITLE
Method for resizing fit to box while preserving proportion.

### ISSUE THREAD

**Issue by jinahya** [thebuzzmedia/imgscalr#107]
Is there any way to resize to fit in a box while preserving proportion? And positioning to center?

**Comment by thebuzzmedia** [comment]
By default imgscalr will honor the image proportions - but not quite sure what you mean by "and positioning to center" - can you give an example?

**Comment by jinahya** [comment]
~~Is there any way to resize to fit in a box while preserving proportion? And positioning to center?~~
Is there any way to resize to fit in a box(width, height) while preserving proportion?

**Comment by thebuzzmedia** [comment]
ahh - it depends on what you mean.

If you mean providing a box like "300x200" and having imgscalr give you back a proportionally correct image that may NOT fit one of those dimensions edge to edge (for example, if it's portrait, it will fit the 200 height and be short on the 300 width) -- then yes, this is what imgscalr does by default.

If you are asking for it to expand the image, potentially cropping it, to make it force-fit a particular dimension while still maintaining proportions - not it does not do this automatically.

It may be easier to talk specifics though if you have a specific example?

**Comment by Kpaxx** [comment]
I think what jinahya is looking for is resize Mode.BEST_FIT_BOTH, which is not included in the most recent release, version 4.2.

**Comment by thebuzzmedia** [comment]
Ah! Thanks @Kpaxx 

@jinahya If this is the case, you can pull the repo and build it with the included Ant script - BEST_FIT_BOTH is added in the current source, I just haven't pushed a 4.2++ build yet with it.

**Comment by thebuzzmedia** [comment]
Closing. Please re-open if that doesn't address what you needed.

**Comment by jinahya** [comment]
Thanks guys. I'm not sure the `BEST_FIT_BOTH` is what I've been looking for. Please take a look at my code and please tell me that I'm not reinventing the wheel. https://github.com/jinahya/jinahya-imgscalr-lib/blob/develop/src/main/java/com/github/jinahya/imgscalr/Scalr.java

**Comment by thebuzzmedia** [comment]
Jin - for the sake of walking through this code, can you describe in words
what you are trying to accomplish? for example "if I have an image of
320x200, and target dimensions of 128x64, the algorithm does..." ?

----------------
Riyad
http://thebuzzmedia.com

**Comment by thebuzzmedia** [comment]
Nevermind! I just saw your reply to the other issue. You are correct, if
you are doing both a crop and a fit, this is not something that imgscalr
supports right now - all operations are non-destructive (well, except for
'crop' itself that is :), if you need destructive behavior that is
currently custom impl.


----------------
Riyad
http://thebuzzmedia.com
